export const labels = {
  en: {
    systemName: 'Sistem E-Booking SK Bebuloh',
    availabilityTitle: 'Availability Overview',
    availabilitySubtitle: 'Select a room to view available time slots.',
    loadingAvailability: 'Loading availability…',
    syncingSchedule: 'Syncing live schedule.',
    unableLoad: 'Unable to load schedule',
    noRoomsTitle: 'No rooms available',
    noRoomsMeta: 'Please contact the administrator.',
    today: 'Today',
    thisWeek: 'This Week',
    nextAvailable: 'Next available',
    fullyBookedToday: 'Fully booked today',
    fullyBookedWeek: 'Fully booked this week',
    noSlots: 'No available slots',
    roomFocusTitle: 'Room Focus',
    bookingSheetTitle: 'Confirm Booking',
    bookingRoom: 'Room',
    bookingDate: 'Date',
    bookingTime: 'Time',
    teacherName: 'Teacher name',
    classLabel: 'Class',
    subjectLabel: 'Subject',
    confirmBooking: 'Confirm Booking',
    selectClass: 'Select class',
    selectSubject: 'Select subject',
    enterClass: 'Enter new class',
    enterSubject: 'Enter new subject',
    addNew: 'Add new',
    available: 'Available',
    booked: 'Booked',
    closed: 'Closed',
    recess: 'Recess',
    teachingSlot: 'Teaching slot',
    disabled: 'Unavailable',
    alreadyBooked: 'This slot has already been booked.',
    formIncomplete: 'Please complete all booking details.',
    bookingSuccess: 'Booking confirmed.',
    adminTitle: 'Admin Panel',
    adminSubtitle: 'Bookings for this week',
    adminSignOut: 'Sign out',
    adminLogin: 'Admin login',
    noBookingsTitle: 'No bookings yet'
  },
  bm: {
    systemName: 'Sistem E-Booking SK Bebuloh',
    availabilityTitle: 'Gambaran Ketersediaan',
    availabilitySubtitle: 'Pilih bilik untuk melihat slot masa.',
    loadingAvailability: 'Memuatkan ketersediaan…',
    syncingSchedule: 'Menyegerakkan jadual langsung.',
    unableLoad: 'Tidak dapat memuatkan jadual',
    noRoomsTitle: 'Tiada bilik tersedia',
    noRoomsMeta: 'Sila hubungi pentadbir.',
    today: 'Hari Ini',
    thisWeek: 'Minggu Ini',
    nextAvailable: 'Slot seterusnya',
    fullyBookedToday: 'Penuh hari ini',
    fullyBookedWeek: 'Penuh minggu ini',
    noSlots: 'Tiada slot tersedia',
    roomFocusTitle: 'Fokus Bilik',
    bookingSheetTitle: 'Sahkan Tempahan',
    bookingRoom: 'Bilik',
    bookingDate: 'Tarikh',
    bookingTime: 'Masa',
    teacherName: 'Nama guru',
    classLabel: 'Kelas',
    subjectLabel: 'Subjek',
    confirmBooking: 'Sahkan Tempahan',
    selectClass: 'Pilih kelas',
    selectSubject: 'Pilih subjek',
    enterClass: 'Masukkan kelas baharu',
    enterSubject: 'Masukkan subjek baharu',
    addNew: 'Tambah baharu',
    available: 'Tersedia',
    booked: 'Ditempah',
    closed: 'Ditutup',
    recess: 'Rehat',
    teachingSlot: 'Slot pengajaran',
    disabled: 'Tidak tersedia',
    alreadyBooked: 'Slot ini telah ditempah.',
    formIncomplete: 'Sila lengkapkan maklumat tempahan.',
    bookingSuccess: 'Tempahan disahkan.',
    adminTitle: 'Panel Admin',
    adminSubtitle: 'Tempahan minggu ini',
    adminSignOut: 'Log keluar',
    adminLogin: 'Log masuk admin',
    noBookingsTitle: 'Belum ada tempahan'
  }
}
