export const labels = {
  en: {
    systemName: 'Sistem E-Booking SK Bebuloh',
    systemMeta: 'Internal booking workspace',
    availabilityTitle: 'Availability Overview',
    availabilitySubtitle: 'Tap a room to view real-time slots.',
    loadingAvailability: 'Loading availability…',
    syncingSchedule: 'Syncing live schedule.',
    unableLoad: 'Unable to load schedule',
    noRoomsTitle: 'No rooms available',
    noRoomsMeta: 'Please contact the administrator.',
    today: 'Today',
    thisWeek: 'This Week',
    nextAvailable: 'Next available',
    fullyBookedToday: 'Fully booked today',
    fullyBookedWeek: 'Fully booked this week',
    noSlots: 'No available slots',
    roomFocusTitle: 'Room Focus',
    bookingSheetTitle: 'Confirm Booking',
    bookingRoom: 'Room',
    bookingDate: 'Date',
    bookingTime: 'Time',
    teacherName: 'Teacher',
    classLabel: 'Class',
    subjectLabel: 'Subject',
    confirmBooking: 'Confirm Booking',
    selectClass: 'Select class',
    selectSubject: 'Select subject',
    selectTeacher: 'Select teacher',
    enterClass: 'Enter new class',
    enterSubject: 'Enter new subject',
    addNew: 'Add new',
    available: 'Available',
    booked: 'Booked',
    closed: 'Closed',
    recess: 'Recess',
    teachingSlot: 'Teaching slot',
    disabled: 'Unavailable',
    alreadyBooked: 'This slot has already been booked.',
    formIncomplete: 'Please complete all booking details.',
    bookingSuccess: 'Booking confirmed.',
    bookingSuccessTitle: 'Booking confirmed',
    bookingSuccessMeta: 'You are all set for this room.',
    adminTitle: 'Admin Panel',
    adminSubtitle: 'Bookings for this week',
    adminSignOut: 'Sign out',
    adminLogin: 'Admin login',
    noBookingsTitle: 'No bookings yet',
    teacherEmpty: 'No teachers available',
    classEmpty: 'No classes available',
    subjectEmpty: 'No subjects yet',
    addSubject: 'Add new subject',
    addClass: 'Add new class',
    addTeacher: 'Add new teacher',
    bookingCTA: 'Confirm booking',
    bookingDisabled: 'Complete all details to continue',
    segmentedHelp: 'Today / This week',
    statusBooked: 'Booked',
    statusClosed: 'Closed (10 min rule)',
    statusRecess: 'Recess',
    statusAvailable: 'Available',
    statusUnavailable: 'Unavailable',
    teachersTitle: 'Teachers',
    classesTitle: 'Classes',
    subjectsTitle: 'Subjects',
    tahapLabel: 'Tahap',
    classTahapOne: 'Tahap 1',
    classTahapTwo: 'Tahap 2',
    tapToView: 'Tap to view'
  },
  bm: {
    systemName: 'Sistem E-Booking SK Bebuloh',
    systemMeta: 'Ruang tempahan dalaman',
    availabilityTitle: 'Gambaran Ketersediaan',
    availabilitySubtitle: 'Tekan bilik untuk melihat slot masa langsung.',
    loadingAvailability: 'Memuatkan ketersediaan…',
    syncingSchedule: 'Menyegerakkan jadual langsung.',
    unableLoad: 'Tidak dapat memuatkan jadual',
    noRoomsTitle: 'Tiada bilik tersedia',
    noRoomsMeta: 'Sila hubungi pentadbir.',
    today: 'Hari Ini',
    thisWeek: 'Minggu Ini',
    nextAvailable: 'Slot seterusnya',
    fullyBookedToday: 'Penuh hari ini',
    fullyBookedWeek: 'Penuh minggu ini',
    noSlots: 'Tiada slot tersedia',
    roomFocusTitle: 'Fokus Bilik',
    bookingSheetTitle: 'Sahkan Tempahan',
    bookingRoom: 'Bilik',
    bookingDate: 'Tarikh',
    bookingTime: 'Masa',
    teacherName: 'Guru',
    classLabel: 'Kelas',
    subjectLabel: 'Subjek',
    confirmBooking: 'Sahkan Tempahan',
    selectClass: 'Pilih kelas',
    selectSubject: 'Pilih subjek',
    selectTeacher: 'Pilih guru',
    enterClass: 'Masukkan kelas baharu',
    enterSubject: 'Masukkan subjek baharu',
    addNew: 'Tambah baharu',
    available: 'Tersedia',
    booked: 'Ditempah',
    closed: 'Ditutup',
    recess: 'Rehat',
    teachingSlot: 'Slot pengajaran',
    disabled: 'Tidak tersedia',
    alreadyBooked: 'Slot ini telah ditempah.',
    formIncomplete: 'Sila lengkapkan maklumat tempahan.',
    bookingSuccess: 'Tempahan disahkan.',
    bookingSuccessTitle: 'Tempahan disahkan',
    bookingSuccessMeta: 'Bilik ini telah ditempah.',
    adminTitle: 'Panel Admin',
    adminSubtitle: 'Tempahan minggu ini',
    adminSignOut: 'Log keluar',
    adminLogin: 'Log masuk admin',
    noBookingsTitle: 'Belum ada tempahan',
    teacherEmpty: 'Tiada guru tersedia',
    classEmpty: 'Tiada kelas tersedia',
    subjectEmpty: 'Belum ada subjek',
    addSubject: 'Tambah subjek baharu',
    addClass: 'Tambah kelas baharu',
    addTeacher: 'Tambah guru baharu',
    bookingCTA: 'Sahkan tempahan',
    bookingDisabled: 'Lengkapkan maklumat untuk meneruskan',
    segmentedHelp: 'Hari ini / Minggu ini',
    statusBooked: 'Ditempah',
    statusClosed: 'Ditutup (10 minit)',
    statusRecess: 'Rehat',
    statusAvailable: 'Tersedia',
    statusUnavailable: 'Tidak tersedia',
    teachersTitle: 'Guru',
    classesTitle: 'Kelas',
    subjectsTitle: 'Subjek',
    tahapLabel: 'Tahap',
    classTahapOne: 'Tahap 1',
    classTahapTwo: 'Tahap 2',
    tapToView: 'Tekan untuk lihat'
  }
}
